2024-11-23 14:35:48,340 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\МЫ\PycharmProjects\pythonProject\.venv\tests_12_4.py", line 25, in test_run
    r2 = Runner(4)
         ^^^^^^^^^
  File "C:\Users\МЫ\PycharmProjects\pythonProject\.venv\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-11-23 14:35:48,341 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\МЫ\PycharmProjects\pythonProject\.venv\tests_12_4.py", line 14, in test_walk
    r1 = Runner('Usain Bolt', -50)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\МЫ\PycharmProjects\pythonProject\.venv\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -50
